### ISSUE TITLE
add iojs back into travis config once node-sass is in a better state

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/idea-town#41]
https://github.com/mozilla/fxa-auth-db-server/blob/master/.travis.yml#L33-L38

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/fxa-auth-db-server/blob/master/.travis.yml#L33-L38
```yaml
matrix:
  allow_failures:
    - node_js: "0.12"
    - node_js: "iojs"
  fast_finish: true
```
