### ISSUE TITLE
Based on css urls, Tabzilla graphics shouldn't be showing up, but are.

### ISSUE THREAD

**Issue by johngruen** [mozilla/idea-town#85]
Not totally sure what's going on here. Somehow, the tabzilla graphic is loading correctly on the site even though it isn't in the right place. 

In `main.min.css` tabzilla graphic is pointing to `../media/img/tabzilla-static.png`

The assets are actually at `../vendor/mozilla-tabzilla/media/img/tabzilla-static.png`

Here's the weird thing...if you `rm -rf public/vendor` the tabzilla graphic disappears from the site, but if you `mv` the tabzilla graphics to the `../media/img/tabzilla-static.png` it shows back up.

I think there's some kind of wormhole being ripped open by some combination of gulp, sass and node, but I'm really not sure. It's an easy fix, but I'd be interested in the cause if anybody has a guess. @pdehaan seems particularly well suited to diagnosing this issue.

**Comment by pdehaan** [comment]
I don't quite know what's happening, but I have a possible explanation and workaround.

We have a /public/styles/main.css file that concatenates the **mozilla-tabzilla** code (amongst other things). It has the following sauce:

```css
#tabzilla a {
  background-image: url("../media/img/tabzilla-static.png");
  /* ... */ }

@media (-webkit-min-device-pixel-ratio: 1.5),
    (min--moz-device-pixel-ratio: 1.5),
    (min-resolution: 1.5dppx) {
  #tabzilla a {
    background-image: url("../media/img/tabzilla-static-high-res.png");
    background-size: 147px 37px; } }
```

So, since the /public directory is our server's static home directory, it ends up looking for a `../media/**` (which is the same as `/media/**` in this case). No harm, no foul because we happen to have a workaround from a previous Tabzilla issue (https://github.com/mozilla/tabzilla/pull/66) where we were remapping the absolute `/media/**` path to `./public/vendor/mozilla/tabzilla/media/**`. So everything works and images resolve, etc.

---

Workaround seems simple enough, instead of copying the **mozilla-tabzilla** module's `/media/` directory to the `./public/vendor/**` directory [[1](https://github.com/mozilla/idea-town/blob/69231924f82164b492fd31166a88ae3ae1270938/gulpfile.js#L89-L92)], we copy it directly to `./public/media/**` and then can remove that `app.use('/media')` alias from ./server.js [[2](https://github.com/mozilla/idea-town/blob/69231924f82164b492fd31166a88ae3ae1270938/server.js#L18)].

[[1] ./gulpfile.js:89-92](https://github.com/mozilla/idea-town/blob/69231924f82164b492fd31166a88ae3ae1270938/gulpfile.js#L89-L92)
[[2] ./server.js:18](https://github.com/mozilla/idea-town/blob/69231924f82164b492fd31166a88ae3ae1270938/server.js#L18)
